import { defineConfig } from "oxlint";
import dividConfig from "oxlint-config-divid";

export default defineConfig({
  extends: [dividConfig],
  ignorePatterns: [
    "**/lib/**",
    "**/node_modules/**",
    "**/dist/**",
    "**/build-storybook/**",
    "packages/*/public/**",
    // Generated 3D-scene data, not hand-written example code.
    "packages/abstract-visuals-example/src/app/systemair*.ts",
    "packages/abstract-visuals-example/src/app/vortice.ts",
    "packages/abstract-visuals-example/src/app/demo.ts",
    "packages/abstract-visuals-example/src/app/demo-rotated.ts",
    "packages/abstract-visuals-example/src/app/double-view-component-geometries.ts",
  ],
  jsPlugins: [{ name: "functional", specifier: "eslint-plugin-functional" }],
  rules: {
    "functional/no-let": ["error", { allowInFunctions: true, ignoreIdentifierPattern: "^[mM]utable" }],
    "functional/prefer-property-signatures": "error",

    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/explicit-module-boundary-types": "off",
    "typescript/no-unsafe-assignment": "off",
    "typescript/no-unsafe-call": "off",
    "typescript/no-unsafe-return": "off",
    "typescript/no-unsafe-member-access": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "node/global-require": "off",
    "no-restricted-globals": "off",
    "typescript/no-require-imports": "off",
    "typescript/dot-notation": "off",
    "no-case-declarations": "off",
    "prefer-const": "off",
    "typescript/prefer-nullish-coalescing": "off",
    "typescript/prefer-optional-chain": "off",
    "typescript/no-explicit-any": "off",
    "typescript/no-empty-object-type": "off",
    "typescript/no-wrapper-object-types": "off",
    "typescript/parameter-properties": "off",
    curly: "off",
    "default-case": "off",
    "typescript/array-type": "off",
    "typescript/no-unnecessary-condition": "off",
    "no-useless-return": "off",
    "typescript/ban-tslint-comment": "off",
    eqeqeq: "off",
    "no-throw-literal": "off",
    "typescript/only-throw-error": "off",
    "typescript/unified-signatures": "off",
    "no-bitwise": "off",
    "typescript/no-var-requires": "off",
    "init-declarations": "off",
    "no-shadow": "off",
    "no-empty-pattern": "off",
    "typescript/prefer-string-starts-ends-with": "off",
    "no-restricted-properties": "off",
    "no-unused-vars": "off",
    "typescript/no-unnecessary-boolean-literal-compare": "off",
    "typescript/switch-exhaustiveness-check": "off",
    "typescript/prefer-reduce-type-parameter": "off",
    "one-var": "off",
    "no-prototype-builtins": "off",
    "typescript/prefer-readonly": "off",
    "no-alert": "off",
    "max-lines": ["error", 1100],
    "prefer-object-spread": "off",
    "unicorn/no-array-sort": "off",

    // Flags React components defined inside other components, which is a normal pattern.
    "unicorn/consistent-function-scoping": "off",
    // False-positives on <Namespace.Component /> through an `export *` barrel.
    "import/namespace": "off",
  },
});
