packages:
  - "packages/*"

allowBuilds:
  esbuild: false
  husky: false

minimumReleaseAgeExclude:
  - abstract-3d@2.0.5
  - abstract-chart@12.0.51
  - abstract-document@19.1.1
  - abstract-image@13.0.37
  - abstract-sheet@1.1.22
  - handlebars-xml@0.4.4
  - jsxpression@0.1.34

overrides:
  three-stdlib: "^2.36.0"

packageExtensions:
  tunnel-rat@*:
    peerDependencies:
      react: "^19.0.0"
