packages:
  - "packages/*"

allowBuilds:
  esbuild: false
  husky: false

minimumReleaseAgeExclude:
  - abstract-3d@2.0.3

overrides:
  three-stdlib: "^2.36.0"

packageExtensions:
  tunnel-rat@*:
    peerDependencies:
      react: "^19.0.0"
