import { Scene } from "../../../abstract-3d/src/index.js";

export const cylinderFilter = {
  center_deprecated: {
    x: 620,
    y: 250,
    z: 0,
  },
  size_deprecated: {
    x: 300,
    y: 448.0000000000001,
    z: 949,
  },
  groups: [
    {
      meshes: [],
      pos: {
        x: 500,
        y: 250,
        z: 0,
      },
      rot: {
        x: -3.141592653589793,
        y: 0,
        z: -3.141592653589793,
      },
      data: {
        id: "1b46a081-a1d2-447e-8977-173e66dfa3f6",
        box: "box",
      },
      groups: [
        {
          meshes: [
            // {
            //   geometry: {
            //     type: "Box",
            //     pos: {
            //       x: -150,
            //       y: -1,
            //       z: 0.5,
            //     },
            //     rot: {
            //       x: 0,
            //       y: 0,
            //       z: 0,
            //     },
            //     size: {
            //       x: 20,
            //       y: 450,
            //       z: 950,
            //     },
            //     holes: [],
            //   },
            //   material: {
            //     sort_no: 35,
            //     name: "filt_frame",
            //     type: 0,
            //     shininess: 100,
            //     opacity: 1,
            //     normal: "rgb(120,120,120)",
            //     hover: "rgb(90,90,90)",
            //     selected: "rgb(14,82,184)",
            //     dxf: "1",
            //     metalness: 0.45,
            //     roughness: 0.4,
            //   },
            // },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: 149,
                  z: -379.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: -1,
                  z: -379.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: -151,
                  z: -379.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: 149,
                  z: -189.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: -1,
                  z: -189.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: -151,
                  z: -189.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: 149,
                  z: 0.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: -1,
                  z: 0.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: -151,
                  z: 0.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: 149,
                  z: 190.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: -1,
                  z: 190.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: -151,
                  z: 190.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: 149,
                  z: 380.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: -1,
                  z: 380.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
            {
              geometry: {
                type: "Cylinder",
                pos: {
                  x: 0,
                  y: -151,
                  z: 380.5,
                },
                radius: 81,
                length: 300,
                rot: {
                  x: 0,
                  y: 0,
                  z: 1.5707963267948966,
                },
                holes: [],
              },
              material: {
                sort_no: 39,
                name: "filt_cyl",
                type: 0,
                shininess: 100,
                opacity: 1,
                normal: "rgb(60,60,70)",
                hover: "rgb(30,30,40)",
                selected: "rgb(14,82,184)",
                dxf: "1",
                metalness: 0.45,
                roughness: 0.4,
              },
            },
          ],
          pos: {
            x: -120,
            y: 0,
            z: 0,
          },
          rot: {
            x: 0,
            y: 0,
            z: 0,
          },
          data: {},
          groups: [],
        },
      ],
    },
  ],
  dimensions_deprecated: {
    dimensions: [],
    material: {
      sort_no: 2,
      name: "dimension_light",
      type: 2,
      shininess: 50,
      opacity: 1,
      normal: "rgb(225,225,225)",
      hover: "rgb(225,225,225)",
      selected: "rgb(225,225,225)",
      dxf: "8",
      metalness: 0,
      roughness: 1,
    },
    bounds: {
      front: {
        min: {
          x: 0,
          y: 0,
        },
        max: {
          x: 0,
          y: 0,
        },
      },
      back: {
        min: {
          x: 0,
          y: 0,
        },
        max: {
          x: 0,
          y: 0,
        },
      },
      left: {
        min: {
          x: 0,
          y: 0,
        },
        max: {
          x: 0,
          y: 0,
        },
      },
      right: {
        min: {
          x: 0,
          y: 0,
        },
        max: {
          x: 0,
          y: 0,
        },
      },
      top: {
        min: {
          x: 0,
          y: 0,
        },
        max: {
          x: 0,
          y: 0,
        },
      },
      bottom: {
        min: {
          x: 0,
          y: 0,
        },
        max: {
          x: 0,
          y: 0,
        },
      },
      threeD: {
        min: {
          x: 0,
          y: 0,
          z: 0,
        },
        max: {
          x: 0,
          y: 0,
          z: 0,
        },
      },
    },
  },
} as unknown as Scene;
