/* eslint-disable max-lines */
import { AbstractImage } from "abstract-image";

export const ai = {
  topLeft: {
    x: 0,
    y: 0,
  },
  size: {
    width: 420,
    height: 297,
  },
  backgroundColor: {
    a: 0,
    r: 255,
    g: 255,
    b: 255,
  },
  components: [
    "//section 1",
    {
      type: "rectangle",
      topLeft: {
        x: 269,
        y: 1,
      },
      bottomRight: {
        x: 419,
        y: 296,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
      fillColor: {
        a: 255,
        r: 255,
        g: 255,
        b: 255,
      },
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 8,
      },
      text: "drawing is for bid purposes only, and are subject to change during detailed",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 203,
        b: 62,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 14,
      },
      text: "engineering",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 203,
        b: 62,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    "//section 2",
    {
      type: "line",
      start: {
        x: 269,
        y: 24,
      },
      end: {
        x: 419,
        y: 24,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
    },
    {
      type: "rectangle",
      topLeft: {
        x: 273,
        y: 31,
      },
      bottomRight: {
        x: 277,
        y: 35,
      },
      strokeColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
      fillColor: {
        a: 255,
        r: 255,
        g: 15,
        b: 0,
      },
    },
    {
      type: "text",
      position: {
        x: 274,
        y: 39,
      },
      text: "T",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 285,
        y: 33,
      },
      text: "Electrical switch for power circuit",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 203,
        b: 62,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 285,
        y: 39,
      },
      text: "Door with lever",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 203,
        b: 62,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    "//section 3",
    {
      type: "line",
      start: {
        x: 269,
        y: 47,
      },
      end: {
        x: 419,
        y: 47,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 54.5,
      },
      text: "TH",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 285,
        y: 54.5,
      },
      text: "Tür Standard mit Türgriff",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    "//section 4",
    {
      type: "line",
      start: {
        x: 269,
        y: 64,
      },
      end: {
        x: 419,
        y: 64,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 73,
      },
      text: "ODA",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 285,
        y: 73,
      },
      text: "Außenluft",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 79,
      },
      text: "SUP",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 285,
        y: 79,
      },
      text: "Zuluft",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    "//section 5",
    {
      type: "line",
      start: {
        x: 269,
        y: 87,
      },
      end: {
        x: 419,
        y: 87,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 96,
      },
      text: "Nr.",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 285,
        y: 96,
      },
      text: "Breite",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 313,
        y: 96,
      },
      text: "Höhe",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 343,
        y: 96,
      },
      text: "Länge",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 383,
        y: 96,
      },
      text: "Gewicht",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 102,
      },
      text: "1",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 285,
        y: 102,
      },
      text: "3200",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 313,
        y: 102,
      },
      text: "2600",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 343,
        y: 102,
      },
      text: "1750",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 383,
        y: 102,
      },
      text: "815",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 110,
      },
      text: "Verschiedenes",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 383,
        y: 110,
      },
      text: "517",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    "//section 5",
    {
      type: "line",
      start: {
        x: 269,
        y: 118,
      },
      end: {
        x: 419,
        y: 118,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 127,
      },
      text: "M: 1.75",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 297,
        y: 127,
      },
      text: "|",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 299,
        y: 127,
      },
      text: "Gesamtgewicht Gerät ca. 7,152 [kg]",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    "//section 6",
    {
      type: "line",
      start: {
        x: 269,
        y: 135,
      },
      end: {
        x: 419,
        y: 135,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 144,
      },
      text: "Ausführung: VDI-6022 Gerät für Innenaufstellung",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    "//section 7",
    {
      type: "line",
      start: {
        x: 269,
        y: 152,
      },
      end: {
        x: 419,
        y: 152,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 161,
      },
      text: "1 Stk. Zuluft XPRO17",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    "//section 8",
    {
      type: "line",
      start: {
        x: 269,
        y: 169,
      },
      end: {
        x: 419,
        y: 169,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 178,
      },
      text: "Luftmenge m³/h 70,000",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 184,
      },
      text: "Satischer druck Pa 0",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    "//section 9",
    {
      type: "line",
      start: {
        x: 269,
        y: 192,
      },
      end: {
        x: 419,
        y: 192,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 199,
      },
      text: "Projekt Nr.:",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 303,
        y: 199,
      },
      text: "09 0015",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 205,
      },
      text: "Position:",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 303,
        y: 205,
      },
      text: "001a",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 211,
      },
      text: "Projekt:",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 303,
        y: 211,
      },
      text: "Siemens Halle 60",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 217,
      },
      text: "Anl.:",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 303,
        y: 217,
      },
      text: "Zentrale Nord",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 223,
      },
      text: "Kund:",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 303,
        y: 223,
      },
      text: "WOWI Haustechnik GmbH",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    "//section 10",
    {
      type: "line",
      start: {
        x: 269,
        y: 229,
      },
      end: {
        x: 419,
        y: 229,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 236,
      },
      text: "gezeichnet: DIN A4",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    {
      type: "text",
      position: {
        x: 273,
        y: 242,
      },
      text: "Datum: 19.03.2009",
      fontFamily: "",
      fontSize: 4,
      textColor: {
        a: 255,
        r: 255,
        g: 0,
        b: 0,
      },
      fontWeight: "normal",
      clockwiseRotationDegrees: 0,
      textAlignment: "left",
      horizontalGrowthDirection: "right",
      verticalGrowthDirection: "down",
      strokeThickness: 0,
      strokeColor: {
        a: 0,
        r: 255,
        g: 255,
        b: 255,
      },
      italic: false,
    },
    "//section 11",
    {
      type: "line",
      start: {
        x: 269,
        y: 251,
      },
      end: {
        x: 419,
        y: 251,
      },
      strokeColor: {
        a: 255,
        r: 0,
        g: 0,
        b: 0,
      },
      strokeThickness: 1,
      strokeDashStyle: {
        dashes: [],
        offset: 0,
      },
    },
    "//ahu front & top",
    {
      type: "binaryimage",
      topLeft: {
        x: 0,
        y: 19.25,
      },
      bottomRight: {
        x: 270,
        y: 239.25,
      },
      format: "png",
      data: {
        type: "url",
        url: "/image/component-geometry/35156100-5bba-4926-ac3f-7368c9dfe0b9/348a1ad1-5f0e-4745-8f46-be2b49e7df21?type=ComponentGeometryImage&language=en-GB&cols=0&rows=0&views=%5B%7B%22split_casing_layers%22%3Afalse%2C%22titles%22%3A%5B%5D%2C%22view%22%3A%22front%22%2C%22detail_level%22%3A%22detailed%22%2C%22rotation%22%3A0%7D%2C%7B%22split_casing_layers%22%3Afalse%2C%22titles%22%3A%5B%5D%2C%22view%22%3A%22top%22%2C%22detail_level%22%3A%22detailed%22%2C%22rotation%22%3A0%7D%5D",
      },
    },
  ],
} as AbstractImage;
