name: CI

on: [push]

jobs:
  lint:
    name: Linting Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Linting Checks
        run: pnpm lint

  test:
    name: "Test - Node: ${{ matrix.node_version }} - OS: ${{ matrix.os }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        os:
          - "ubuntu-latest"
        node_version:
          - "18"
          - "20"
          - "22"

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: pnpm install
        run: pnpm install

      - name: lint
        run: pnpm lint

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test-coverage

      - name: Report coverage
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
